### ISSUE TITLE
关于终极清洗工厂的bug

### ISSUE THREAD

**Issue by byg911** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#10]
终极清洗工厂的左右两面应是要连接加压管道，而顶部应连接机械管道
但是在我游玩时发现，清洗工厂的顶部并不能连接机械管道

**Comment by byg911** [comment]
![1708691728981](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/121806039/5cb37424-e270-4bd1-808a-3f4656aade2a)
![Uploading 1708691751130.jpg…]()
![Uploading 1708691772804.jpg…]()

**Comment by byg911** [comment]
![Uploading 1708692957036.jpg…]()

**Comment by sddsd2332** [comment]
使用构建版本

**Comment by byg911** [comment]
不会构建怎么办



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月23日 21:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sddsd2332/Mekanism-CE-Unofficial-1.12.2] 关于终极清洗工厂的bug (Issue #10) |

使用构建版本

**Comment by sddsd2332** [comment]
已上传cf，等过审
或从mcmod上下载

**Comment by byg911** [comment]
对了，还有两个bug

一个是关于自动弹出气体功能的bug

当机器使用自动弹出时他会弹出作为原材料的气体，而不是弹出作为产品的气体
例如
终极溶解工厂内有浆液和硫酸时，将会弹出硫酸

还有一个bug是关于创造工厂的
创造工厂不会弹出气体
我电脑已经关机了，所以没截图，不过我已经设置好了输入和输出



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月23日 22:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sddsd2332/Mekanism-CE-Unofficial-1.12.2] 关于终极清洗工厂的bug (Issue #10) |

已上传cf，等过审
或从mcmod上下载
