### ISSUE TITLE
[Enhancement] Add In and Output on the same side like in newer Mekanism versions

### ISSUE THREAD

**Issue by Semetix** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#15]
As the Title says, in Mek Versions past 1.12.2 you are able to in and output from the same side.

Would be highly appreciated if it is possible to be added.

**Comment by sddsd2332** [comment]
There is no way to achieve this for the time being
There may be a big overhaul of the way the slot is done

**Comment by sddsd2332** [comment]
Done this without overhauling, closing the issue
If you need a file, download it [here](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/actions/runs/8959602574)

**Comment by Semetix** [comment]
Is it planned to merge this with Mekanism Community Edition, or is this your own Version?
