### ISSUE TITLE
[Bug] 化学灌注器在最新版本中存在错误

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#21]
1.侧面输入输出的配置界面中缺失部分模式的文本
2. GUI 中右侧槽位放置气罐不会输入，但是可以使用管道导入

**Comment by sddsd2332** [comment]
>1.侧面输入输出的配置界面中缺失部分模式的文本

这个加个文本就行
>2.GUI 中右侧槽位放置气罐不会输入，但是可以使用管道导入

这个无法复现，请检测是否有配方，如果你是指导管导入的时候，会重复的相同的气体，这个是暂时不处理的

**Comment by zeng-github01** [comment]
> >1.侧面输入输出的配置界面中缺失部分模式的文本
> 
> 这个加个文本就行
> >2.GUI 中右侧槽位放置气罐不会输入，但是可以使用管道导入
> 
> 这个无法复现，请检测是否有配方，如果你是指导管导入的时候，会重复的相同的气体，这个是暂时不处理的

关于第二个问题，估计是我记错了，是左侧，总之是有一侧放不进的。
