### ISSUE TITLE
[Bug]部分机器的侧面气体配置无法修改模式

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#25]
例如氧化机的输入改输出

**Comment by sddsd2332** [comment]
? 确定？
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/21332467/b971145a-48af-4f4a-b3cf-b4e31d7103bf)
我这边可以正常输出

**Comment by sddsd2332** [comment]
是工厂版本的吗？

**Comment by zeng-github01** [comment]
> 是工厂版本的吗？

是的 目前已经确认不是所有机器都有这个问题。很难说是什么导致的
Bug 触发后的行为看起来像是，在切换的一瞬间被撤回操作
并且使用配置器也不能修改，处于完全的瘫痪状态。如果尝试使用配置器，就会发现虽然方块侧面颜色已经变更，但是回到侧面设置还是没有变。然后再掏出配置器就会发现变回去了

**Comment by zeng-github01** [comment]
同时所使用的Mod版本为 [这个](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/commit/9343da02b99629130869992086dee7a0f4432abe)

**Comment by zeng-github01** [comment]
@sddsd2332 还有就是需要修正一下，灌注器的Bug 是描述错误，应该是左侧的槽位有错误，不是右侧，总之只有一边有这个问题。可以使用管道进行输入，但是放罐子进插槽不会抽出。

中间我查看过，确定是没有什么1mB的残留这种恶心的玩意

**Comment by sddsd2332** [comment]
> @sddsd2332 还有就是需要修正一下，灌注器的Bug 是描述错误，应该是左侧的槽位有错误，不是右侧，总之只有一边有这个问题。可以使用管道进行输入，但是放罐子进插槽不会抽出。
> 中间我查看过，确定是没有什么1mB的残留这种恶心的玩意

无法复现，我这边插槽可以正常的抽出气体，建议发视频


> > 是工厂版本的吗？
> 
> 是的 目前已经确认不是所有机器都有这个问题。很难说是什么导致的 Bug 触发后的行为看起来像是，在切换的一瞬间被撤回操作 并且使用配置器也不能修改，处于完全的瘫痪状态。如果尝试使用配置器，就会发现虽然方块侧面颜色已经变更，但是回到侧面设置还是没有变。然后再掏出配置器就会发现变回去了

已经修复，加了个检查，只触发一次而不是循环触发
