### ISSUE TITLE
最新版本化学灌注器-插槽功能异常

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#26]
故障问题更新，不是某一个插槽有问题，是插槽逻辑存在错误，灌注器存在左右两个插槽
当其中一个插槽存在气体时，另一个插槽就会无法使用气罐插入气体。此时仅支持管道输入

其中不包含中间产物槽

@sddsd2332

**Comment by sddsd2332** [comment]
发视频，光说没用

**Comment by zeng-github01** [comment]
> 发视频，光说没用

给个邮箱,Github 只能发10M，没找到方法压

**Comment by sddsd2332** [comment]
直接上传git，用QQ录制，我这边没法复现

https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/21332467/46f4d0ce-6ac7-4e8f-8bfd-cdacab07ff3c

**Comment by zeng-github01** [comment]
不知道怎么传上去，我这只能传文件。大小还只有10M

**Comment by sddsd2332** [comment]
是普通的储罐是吧

**Comment by zeng-github01** [comment]
> 是普通的储罐是吧

终极储罐

**Comment by zeng-github01** [comment]
暂时也弄不懂什么情况。两个气体槽只能用罐子放一个。另一个放不进。要不是不太好接管子，还发现不了这个问题

**Comment by zeng-github01** [comment]
@sddsd2332 视频主要是传不上来，50秒的视频都不能传，鬼知道怎么压才能压到10M

**Comment by zeng-github01** [comment]
> 直接上传git，用QQ录制，我这边没法复现
> 
>  QQ2024521-163330.mp4

我按你的试一下

**Comment by sddsd2332** [comment]
神奇 我不知道是什么问题

**Comment by zeng-github01** [comment]
> 神奇 我不知道是什么问题

你的视频在我这里也能用，我换别的罐子和配方试一下，先挂在这里

**Comment by zeng-github01** [comment]
@sddsd2332 信息更新： 该问题配方在创造储罐下正常，其余储罐异常。已测试基础和终极储罐

再次更新。使用创造储罐先行刷新灌注器，该bug可完成修复

**Comment by zeng-github01** [comment]
例如如果触发该bug ，通过在两个GUI插槽放置对应的创造储罐以完成填充后，所有的普通储罐的功能均恢复正常
@sddsd2332

**Comment by zeng-github01** [comment]
Bug行为在多次进行测试后改变，变为两个槽位都不能使用储罐。但是依然可以使用创造储罐刷新。刷新时的逻辑如下：
如果当前槽位的气体未消耗殆尽，则可以使用普通储罐填充。反之则不可以。也就是说，使用创造储罐进行刷新之后。如果两个槽位的原料都消耗完毕，则两个槽位都无法使用储罐填充。但是创造储罐不受影响

@sddsd2332

**Comment by zeng-github01** [comment]
> Bug行为在多次进行测试后改变，变为两个槽位都不能使用储罐。但是依然可以使用创造储罐刷新。刷新时的逻辑如下： 如果当前槽位的气体未消耗殆尽，则可以使用普通储罐填充。反之则不可以。也就是说，使用创造储罐进行刷新之后。如果两个槽位的原料都消耗完毕，则两个槽位都无法使用储罐填充。但是创造储罐不受影响
> 
> @sddsd2332

介于这个行为，我怀疑是不是在储罐插入时有过滤器。这个过滤器的实现存在bug

**Comment by sddsd2332** [comment]
试试新构建？ 应该可以了

**Comment by zeng-github01** [comment]
> 试试新构建？ 应该可以了

稍后测试

**Comment by zeng-github01** [comment]
确认已修复
