### ISSUE TITLE
关于气体的单面输入输出有一个问题

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#29]
AE2暂时没有相关组件可以在单面同时接收产物。是否需要同时提供一个仅输入的二合一，而不是三合一

**Comment by sddsd2332** [comment]
先不管，先做了再说，如果后面AE有了就不用加了

**Comment by sddsd2332** [comment]
还可以，这样就可以在一个面同时输入物品，气体，流体和能量了

https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/21332467/72bbce4f-bdbc-445f-8584-81002f458440

**Comment by zeng-github01** [comment]
> 还可以，这样就可以在一个面同时输入物品，气体，流体和能量了
> 
> https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/21332467/72bbce4f-bdbc-445f-8584-81002f458440
> 
> 

我发现我那个二合一的输入其实没有删 指灌注器的那个，那刚好了
