### ISSUE TITLE
[Suggestion] More functionality / alternative to Fluorite

### ISSUE THREAD

**Issue by xJon** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#30]
Currently there is only one functionality for Fluorite despite being a whole other ore type. It'd be useful if there were more uses for it, even cosmetic ones for building, or if there was a config option to remove the dependency on it for progressing through the mod.

**Comment by zeng-github01** [comment]
> Currently there is only one functionality for Fluorite despite being a whole other ore type. It'd be useful if there were more uses for it, even cosmetic ones for building, or if there was a config option to remove the dependency on it for progressing through the mod.

Fluorite was added just for syncing the Mek V10 content. The functions of Fluorite in V10 are currently these.

So nothing needs to be added. As for alternatives, equivalent items from NuclearCraft are already available in development builds

**Comment by xJon** [comment]
> Fluorite was added just for syncing the Mek V10 content. The functions of Fluorite in V10 are currently these.
So nothing needs to be added.

I'm not suggesting this in order to match any particular backporting standard, but as a general improvement to the mod as a standalone addition to 1.12.2 modpacks.

> As for alternatives, equivalent items from NuclearCraft are already available in development builds

Would be nice to have alternatives that are not dependent on NuclearCraft (as not all modpacks use it).

**Comment by zeng-github01** [comment]
> > Fluorite was added just for syncing the Mek V10 content. The functions of Fluorite in V10 are currently these.
> > So nothing needs to be added.
> 
> I'm not suggesting this in order to match any particular backporting standard, but as a general improvement to the mod as a standalone addition to 1.12.2 modpacks.
> 
> > As for alternatives, equivalent items from NuclearCraft are already available in development builds
> 
> Would be nice to have alternatives that are not dependent on NuclearCraft (as not all modpacks use it).

So how do you want to improve? Because this item cannot be deleted. This is required for backporting. But there is no need to use it as a decoration

**Comment by zeng-github01** [comment]
@xJon By the way, does your modpack use NuclearCraft? If so. It is recommended that you perform an update. Recent releases have added automatic output of machine products.

**Comment by xJon** [comment]
@zeng-github01 My modpack does not use NuclearCraft

> So how do you want to improve? Because this item cannot be deleted. This is required for backporting. But there is no need to use it as a decoration

It is not true that it's strictly required for backporting.

Notice how in modern Mekanism, Fluorite Dust is required for Polonium Pellet or Plutonium Pellet:
![Untitled](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/ff3148bc-e814-4e34-adc5-7fc7d4b342db)
Yet in CE-Unofficial, Charcoal Dust is required instead:
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/c9c01666-71f8-4347-a764-53794e7f3c00)
Similarly with the recipe for the Chemical Crystallizer.

In CE-Unofficial, it is only used for Hydrofluoric Acid, so I am suggesting to offer an alternative that does not require it.
Another idea is at least to implement the Fluorite Block from modern Mekanism that could be used decoratively, although personally I'd much prefer an alternative recipe for Hydrofluoric Acid so I could simply disable Fluorite Ore generation.

**Comment by zeng-github01** [comment]
> @zeng-github01 My modpack does not use NuclearCraft
> 
> > So how do you want to improve? Because this item cannot be deleted. This is required for backporting. But there is no need to use it as a decoration
> 
> It is not true that it's strictly required for backporting.
> 
> Notice how in modern Mekanism, Fluorite Dust is required for Polonium Pellet or Plutonium Pellet: ![Untitled](https://private-user-images.githubusercontent.com/8945347/332894592-ff3148bc-e814-4e34-adc5-7fc7d4b342db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTg4MDksIm5iZiI6MTcxNjM5ODUwOSwicGF0aCI6Ii84OTQ1MzQ3LzMzMjg5NDU5Mi1mZjMxNDhiYy1lODE0LTRlMzQtYWRjNS03ZmM3ZDRiMzQyZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTcyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzRkZjNjMTgwMDBhODQzMjkxZDRkNDE3ZTBiOTk4ZGEwYmVmNjk2YjA0NDYxNDIzNjkyZDM0ZmE4ZDViODYyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.71oKSU2aU0pg4AH_jS-USTh1ERky10JxCjbPAPNFbf8) Yet in CE-Unofficial, Charcoal Dust is required instead: ![image](https://private-user-images.githubusercontent.com/8945347/332896545-c9c01666-71f8-4347-a764-53794e7f3c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTg4MDksIm5iZiI6MTcxNjM5ODUwOSwicGF0aCI6Ii84OTQ1MzQ3LzMzMjg5NjU0NS1jOWMwMTY2Ni03MWY4LTQzNDctYTc2NC01Mzc5NGU3ZjNjMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTcyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU1ZTlkZTY5NzE5MjY1NWY2OGQ4NTczMjg2NWQwNzNlOTJhYWE4MGE2YjI0Zjk1ZGJjYjYxM2VkN2YyM2YzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q8kWhIJt1TaMSkzloDxjak6V-vregkhk2FXbE_86rU8) Similarly with the recipe for the Chemical Crystallizer.
> 
> In CE-Unofficial, it is only used for Hydrofluoric Acid, so I am suggesting to offer an alternative that does not require it (it also appears impossible to do via CraftTweaker). Another idea is at least to implement the Fluorite Block from modern Mekanism that could be used decoratively, although personally I'd much prefer an alternative recipe for Hydrofluoric Acid so I could simply disable Fluorite Ore generation.

This is obviously a mistake, if that's what you're referring to. Not intentionally. Because this part of the content has not actually been completely completed backport

I've noticed this issue before, considering it hasn't been completed yet. so i ignored it

**Comment by zeng-github01** [comment]
@sddsd2332 大佬来修一下Bug。钋球和钚球的合成表搞错原材料了

**Comment by xJon** [comment]
@zeng-github01 Even when "matching" modern Mekanism I disagree with the mod's design choice of creating a whole extra ore type only for a few end game features. If you disagree, that's fine - I'd just have to implement alternative recipes for my modpack only.

**Comment by zeng-github01** [comment]
> @zeng-github01 Even when "matching" modern Mekanism I disagree with the mod's design choice of creating a whole extra ore type only for a few end game features. If you disagree, that's fine - I'd just have to implement alternative recipes for my modpack only.

I think your choice is the right one. Objectively speaking, you can see a lot of unfinished V10 content in the item list of this branch. This is part of this project. So individual peeling is not possible. The best result would be to add a switch for V10 content. However, the feasibility needs to be evaluated by the developer himself

**Comment by sddsd2332** [comment]
Close this issue
These recipes are now required for Meka armor
