### ISSUE TITLE
Hide WIP content

### ISSUE THREAD

**Issue by xJon** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#37]
CNC machines appear to be WIP although not marked as such, with no recipes and incorrect capitalisation.
They do however flood JEI/HEI with their dirt to sand recipes:
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/e0231761-66a7-43ca-a026-7e8ac591dabd)

This makes using the latest CurseForge / Actions build in a public modpack not a great experience, and removing these recipes in HEI is not as easy as hiding the items manually.
If possible, it'd be best if there was an option to hide all WIP content, to make for a polished experience playing the mod.

**Comment by xJon** [comment]
<details>
  <summary>Same concern with these:</summary>

![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/95cdbe46-3e72-4870-a186-8fffc1b36b6d)
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/4c57e214-f868-48ee-a797-a15c819005c9)
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/d20cdc26-8ea8-4568-9d16-6a456028a273)
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/37fd6226-9b8c-436b-90b0-8dbf1e953178)
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/689d94d5-8ffd-40a1-9795-282f7c864104)
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/acbb92dd-7337-439c-9b85-a646cd5a051a)
</details>

**Comment by sddsd2332** [comment]
By shutting down the machine using the profile, you can close the recipe at the same time

**Comment by sddsd2332** [comment]
> Same concern with these:
> ![image](https://private-user-images.githubusercontent.com/8945347/334087034-689d94d5-8ffd-40a1-9795-282f7c864104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTY5MzksIm5iZiI6MTcxNjgxNjYzOSwicGF0aCI6Ii84OTQ1MzQ3LzMzNDA4NzAzNC02ODlkOTRkNS04ZmZkLTQwYTEtOTc5NS0yODJmN2M4NjQxMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMTMzMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk5YmY5NjQ2MDY1NjdiOGJhYjQwNmU0ZTdiNGQ1ZjA3Y2E2NzU1NjJiYTdmNmM2ZDc5NTBiMWRlMzdiMDIwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D6f-SpRJn8C8rqOEvKa703yTRNw_9qbbgB_3-TYK6EA) 

I don't think this type needs to be hidden, because the fusion reactor can be added with multiple different recipes via CRT or GRS

**Comment by xJon** [comment]
>  By shutting down the machine using the profile, you can close the recipe at the same time

Okay, I see these can be disabled via config (although I believe they should be `false` by default for unfinished machines).

> I don't think this type needs to be hidden, because the fusion reactor can be added with multiple different recipes via CRT or GRS

In this case, could you correct the naming of the machines that can be used?

**Comment by sddsd2332** [comment]
Yes, but I'm not very good at English, so I need a PR submission en_us.lang to process it

**Comment by sddsd2332** [comment]
Close this issue
It can be done through CRT or GRS 
Or it can be done by hiding the classification of the jei

**Comment by xJon** [comment]
@sddsd2332 You are right, but it is really challenging to manually find out all of the WIP content to disable it.
As the mod author, you know already exactly everything that is WIP, so it'd be appreciated if you offered a master toggle.
