### ISSUE TITLE
Unused items?

### ISSUE THREAD

**Issue by xJon** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#40]
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/028daca0-8d0e-4428-98bb-c75b941e8b4c)
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/8945347/b7f071b3-ef16-496b-9849-222d3a613105)

**Comment by sddsd2332** [comment]
It turned out that AE could not be added due to nbt, and it was not possible to synthesize serial synthesis, but now it is ready to remove these
