### ISSUE TITLE
[Bug]化学灌注器逻辑错误

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#51]
当完成合成后，如果一侧的槽位为空，因为未知原因，中间槽位的产物，将会被转移到这个空的材料槽。导致流程卡住

**Comment by sddsd2332** [comment]
发视频

**Comment by zeng-github01** [comment]
> 发视频

请稍等

**Comment by zeng-github01** [comment]
@sddsd2332 

演示合成表为富氧水

https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/95841646/1bc4337e-7b3d-4a8e-b7f2-e1c9439cccac

**Comment by sddsd2332** [comment]
你这个是怎么发配到这里面的？
是用了混合存储来进行发配的吗？

**Comment by sddsd2332** [comment]
是用了混合存储的吗？

**Comment by zeng-github01** [comment]
> 你这个是怎么发配到这里面的？ 是用了混合存储来进行发配的吗？

左边是隔壁的气体输出总线。AE的附属，右边是回旋式，水转水蒸气

但是把这个锅扣到AE2上太抽象了

**Comment by sddsd2332** [comment]
截下你的布局图
另外提供下你的化学灌注的气体弹出设置

**Comment by sddsd2332** [comment]
另外提供下你的化学灌注的气体弹出设置

**Comment by zeng-github01** [comment]
@sddsd2332 

![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/95841646/036e88c0-4738-4cce-86f7-0248d0bacd45)

![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/95841646/c432f543-20ca-41dc-ad75-fb0e625b1f82)

**Comment by sddsd2332** [comment]
回旋从右边输入水蒸气
气体接口从左边输入氧气
中间输出富氧水
这个输出的富氧水是直接回到AE里的吗？

**Comment by zeng-github01** [comment]
> 回旋从右边输入水蒸气 气体接口从左边输入氧气 中间输出富氧水 这个输出的富氧水是直接回到AE里的吗？

前面接了加压管道，传到下一个灌注器，做营养液，就是农场用的那个

**Comment by sddsd2332** [comment]
晚上我看看是什么情况 看代码感觉没问题
AE的气体输出是怎么配置的？

**Comment by zeng-github01** [comment]
![image](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/95841646/f78d8ff4-9da1-4f9e-b75f-9704e3315c28)

**Comment by sddsd2332** [comment]
这个me气体输出总线是那个mod的？ 是AEADD还是MekanismEnergistics？

**Comment by zeng-github01** [comment]
> 这个me气体输出总线是那个mod的？ 是AEADD还是MekanismEnergistics？

后者，AEADD那玩意太拉跨了，我还专门打了个补丁把AEADD的数据转移到MekE(之前是)。要不是之前没得选，谁用那玩意，整个气体的组件没一个遵循AE的标准接口的

**Comment by sddsd2332** [comment]
气体配置中间的输出是单独的输出还是输入输出？

**Comment by zeng-github01** [comment]
> 气体配置中间的输出是单独的输出还是输入输出？

仅输出。

额外还提一嘴，我用的那个开发版本不知道是不是老了，有部分的机器，气体通道没有输入输出。这玩意没有设置通配嘛？ 比如抽象类什么的

**Comment by sddsd2332** [comment]
？你用的是什么版本的MEKCEU？另外MekanismEnergistics是什么版本的？

**Comment by zeng-github01** [comment]
> ？你用的是什么版本的MEKCEU？另外MekanismEnergistics是什么版本的？

9.9.013 MekE是0.1.4

作者你的开发版本貌似基本上都不更新版本号，所以我也难说到底是哪一个补丁的版本

**Comment by sddsd2332** [comment]
来试下，把自动弹出关闭后会不会输到另外一个槽里？
并看AE发配到这个化学灌注是多少？ 是不是一样多
另外直接贴着下一个化学灌注开弹出会不会回流

**Comment by sddsd2332** [comment]
并看AE发配到这个化学储罐是多少？ 是不是一样多

**Comment by zeng-github01** [comment]
@sddsd2332 把输出面关了就正常了。自动输出关闭没试过，暂时被堵住了，还得排空。

Bug 已确认，当设置为输出的时候，实际上是输入并输出。假设该面连接的是加压管道，那么之前就输出到管道里的气体，会被输入回机器里

**Comment by sddsd2332** [comment]
就是走的是输入输出是吧

**Comment by zeng-github01** [comment]
> 就是走的是输入输出是吧

可以这么理解，和UI显示不符。怪不得，怎么拿滴管捞了半天了。都没捞干净。马上反应过来估计是把前面管道的气体给抽进来了。

**Comment by sddsd2332** [comment]
发下气体配置你选择的中间的显示，就是鼠标移上去显示什么？
是输入/输出吗

**Comment by zeng-github01** [comment]
> 发下气体配置你选择的中间的显示，就是鼠标移上去显示什么？

蓝色，输出。这个机器是很久之前就放好了的了，那时候都没有输入输出这个选项。
我都是换MekE了反应过来之前放的AE设施已经寄了。来更换的时候才发现的

**Comment by sddsd2332** [comment]
等下，我大概知道了，当时气体配置类型只有三种，然后升级后要重新点下，不然机器会获取元素从第三个变第五个

**Comment by sddsd2332** [comment]
那这个没问题，关闭

**Comment by zeng-github01** [comment]
> 等下，我大概知道了，当时气体配置类型只有三种，然后升级后要重新点下，不然机器会获取元素从第三个变第五个

已经重新轮换过了。这不是之前的配置。只是显示是一样的

**Comment by zeng-github01** [comment]
都轮着点了几次了 @sddsd2332

**Comment by sddsd2332** [comment]
点几次有没有输入输出的显示？如果没有的话需要拆掉重新放置下

**Comment by sddsd2332** [comment]
没有的话拆掉重新放下看看？

**Comment by zeng-github01** [comment]
> 没有的话拆掉重新放下看看？

拆了也是一样的(用配置器拆的)

轮着点的意思就是，这个通道里面的所有的选项我都已经点出来过了，并不是说，放在那里什么都没改过

能在可选模式里看到输入/输出

**Comment by zeng-github01** [comment]
@sddsd2332 且显示为输入/输出 的选项功能是正常的。并不是逻辑写反了

**Comment by sddsd2332** [comment]
等下修 问题出[这里](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/tile/machine/TileEntityChemicalInfuser.java#L203-L205)和[这里](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/tile/machine/TileEntityChemicalInfuser.java#L221-L229)，因为输出气体id为2，就判断上去了

**Comment by zeng-github01** [comment]
> 等下修 问题出[这里](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/tile/machine/TileEntityChemicalInfuser.java#L203-L205)和[这里](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/tile/machine/TileEntityChemicalInfuser.java#L221-L229)，因为输出气体id为2，就判断上去了

OK , 等待中...
