### ISSUE TITLE
与最新的GroovyScript不兼容

### ISSUE THREAD

**Issue by magcicada** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#52]
详见[GroovyScript issue #181](https://github.com/CleanroomMC/GroovyScript/issues/181)
确认是这边需要更新GroovyScript集成来兼容最新版本GroovyScript内容

**Comment by sddsd2332** [comment]
已经在之前的[提交](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/commit/38e9540)中修复
