### ISSUE TITLE
Pressurized factory failure

### ISSUE THREAD

**Issue by A8T1N** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#54]
version:Mekanism-CE-Unofficial-All-9.9.0.013
There is not enough power with the Pressurized factory running with 8 energy and speed upgrades.
Also, the operation is not completed.
![2024-07-06_20 26 54](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/161058439/12c22a44-3378-4c95-9a81-d28da2af5edf)

![2024-07-06_20 23 22](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/assets/161058439/5f7c930b-1527-43bc-98c7-b5f83e01e4d2)

**Comment by sddsd2332** [comment]
>There is not enough power with the Pressurized factory running with 8 energy and speed upgrades.

Speed upgrades can only be installed up to 5 to run a single socket recipe
>Also, the operation is not completed.

This recipe takes [24,000 ticks](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/MekanismRecipe.java#L301-L302) to complete, not because the recipe is not complete
