### ISSUE TITLE
服务端和groovyScript冲突

### ISSUE THREAD

**Issue by zfms4188** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#56]
报错https://pastebin.com/eZSMASyB
https://github.com/CleanroomMC/GroovyScript/issues/181
在gs提交说是 这边的问题 且在社区版已修复 但是v10版本依旧崩溃

(奇怪的是,我在客户端使用不会崩溃,服务端加载就会,使用linux系统+catserver服务端)

**Comment by sddsd2332** [comment]
grs版本？

**Comment by zfms4188** [comment]
> grs版本？

挨个测试 8.0+ 至目前最新版均无法运行

**Comment by sddsd2332** [comment]
下载构建版本的mekceu，在之前的提交修了和grs最新版本的兼容问题
