### ISSUE TITLE
有关辐射功能的提议

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#58]
是否考虑向后移植Mek的辐射功能。因为NC有两个分支版本，可能无法统一。而且也造成了强依赖。

对最新的提交而言

**Comment by sddsd2332** [comment]
nc的辐射只是给meka套添加辐射抗性 并不会造成强依赖

**Comment by zeng-github01** [comment]
> nc的辐射只是给meka套添加辐射抗性 并不会造成强依赖

有没有办法给重制版和非重制版一块兼容？因为我现在用的就是非重制版
