### ISSUE TITLE
尝试添加冶金灌注机相关配方时出现崩溃问题

### ISSUE THREAD

**Issue by xy177** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#64]
在尝试添加冶金灌注机配方和新灌注类型是出现问题，具体状况如下：
1.添加新的灌注类型与汉化无问题，/ct指令可查到；
2.添加新灌注类型的贴图与灌注制作配方无问题，jei可查到且贴图能正常渲染（附图2）；
3.添加物品与灌注物转化的配方后，打开冶金灌注机与jei对应gui会导致游戏崩溃（附错误报告），打开灌注工厂gui不会崩溃但不渲染灌注物贴图（附图2）；
附件包括附图1，2；相关脚本（gz.zs）；错误报告；灌注物贴图（RANBOW）；如仍需其他文件用于判断问题请提醒，我会再做补充；
模组版本为目前最新版（9.9.1.205）
提前为此反馈占用你们的时间表示抱歉。
[附件.zip](https://github.com/user-attachments/files/16643695/default.zip)

**Comment by sddsd2332** [comment]
灌注物贴图 全小写试试

**Comment by sddsd2332** [comment]
这个不是mek本体的问题 是mekatweaker加载顺序问题，请分开写

**Comment by xy177** [comment]
十分感谢您的回答；只是我有一些没完全听懂，我需要将什么和什么分开写，是指新灌注类型注册与配方分开吗
