### ISSUE TITLE
Suggest adding Mystery Agriculture seeds of fluorite

### ISSUE THREAD

**Issue by VillagerGold** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#71]
As the title suggests, for Skyblock, it is difficult to produce fluorite stably. I hope to add a linkage with Mystical Agriculture to enable fluorite production through planting

**Comment by sddsd2332** [comment]
This recipe has already been added

**Comment by VillagerGold** [comment]
But I didn't see the corresponding seed added in the latest version of Curseforge that has already been released
