### ISSUE TITLE
Suggest adding Mystery Agriculture seeds of fluorite

### ISSUE THREAD

**Issue by VillagerGold** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#78]
As the title suggests, for Skyblock, it is difficult to produce fluorite stably. I hope to add a linkage with Mystical Agriculture to enable fluorite production through planting
Please note that it is adding seeds as an item, not a recipe
The suggestion was not successfully resolved last time, and there was no response to the second question. I hope it can be resolved this time

**Comment by sddsd2332** [comment]
Repeat question #71
Please add the recipe yourself via Crt or Grs
