### ISSUE TITLE
Mek 反应堆不再能输出热量

### ISSUE THREAD

**Issue by zeng-github01** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#8]
描述：在最新的Action构建中，在反应堆启动后，无法使用热导线缆向外输出热量。量子传输的热量统计显示0，热导线缆没有出现热量的填充贴图

**Comment by sddsd2332** [comment]
给反应堆加水
因为写主动冷却的时候写错了，只有反应堆的水罐里有水的时候才会输出热量

**Comment by zeng-github01** [comment]
> 给反应堆加水
> 因为写主动冷却的时候写错了，只有反应堆的水罐里有水的时候才会输出热量

这是临时性的修复方案吧？我反应堆下面有锅炉吗。怪怪的，希望下个版本能修

**Comment by sddsd2332** [comment]
恢复到原来的状态，关闭
