### ISSUE TITLE
Can't place machines when having multiple of them in slot

### ISSUE THREAD

**Issue by ghost** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#80]
**Forge version:** 14.23.5.2860
**Mekanism version:** 9.9.1.214
**Affected machines:** all tiers of machines, regular version of machines like  enrichment chamber, osmium compressor etc, teleporter, every tier of energy cube and even more.
I can't place machines if amount of items slot is more than 1.
**example video attached**

https://github.com/user-attachments/assets/736ec743-2d8f-4e27-a253-d8bc8a2f1d83

**Comment by sddsd2332** [comment]
This is intentional
Prevent problems from occurring
