### ISSUE TITLE
The Rotary Condensator of Mekanism CE Unofficial cannot export fluids and gases

### ISSUE THREAD

**Issue by byg911** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#9]
The Rotary Condensator of Mekanism CE Unofficial cannot export fluids and gases
MEK社区版的回旋式气液转换机不能用mek自身的机械管道或其他mod的管道导出流体或气体

**Comment by byg911** [comment]
你好，我检测了侧面的配置，已经配置好了，我发现当我打开流体自动弹出后，它（回旋式气液转换器）便能将流体弹出到紧密放置的相邻容器里，但是依旧无法使用机械管道或其他MOD的流体管道抽取。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月20日 20:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sddsd2332/Mekanism-CE-Unofficial-1.12.2] The Rotary Condensator of Mekanism CE Unofficial cannot export fluids and gases (Issue #9) |

检测侧配置面是否已经配置？
image.png (view on web)
image.png (view on web)

**Comment by sddsd2332** [comment]
是否有视频？

**Comment by sddsd2332** [comment]
另外版本是是否从其它版本升上来的？

**Comment by byg911** [comment]
我使用该社区版替换了原版，因为原版1.12.2没有v10内容

ps：我在录制视频的时候做了以下操作使得该问题自己解决了

我将气液转换器相邻的容器拆除后它又能使用管道抽取液体了

另：我之前发现不能用管道抽取液体时也已经配置了侧面的自动弹出

总之，这个问题莫名其妙的消失了。

谢谢你抽出时间帮我排除问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月20日 20:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sddsd2332/Mekanism-CE-Unofficial-1.12.2] The Rotary Condensator of Mekanism CE Unofficial cannot export fluids and gases (Issue #9) |

另外版本是是否从其它版本升上来的？
